# -*- coding: utf-8 -*-
"""Solving_RL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6RTqLCvhDTIccse4AnjITXGqCPQ2X0g
"""

import numpy as np
import gymnasium as gym
from typing import Optional

"""# Custom Environment"""

class FoodTruck(gym.Env):
    def __init__(self):
        self.v_demand = [100, 200, 300, 400]
        self.p_demand = [0.3, 0.4, 0.2, 0.1]
        self.capacity = self.v_demand[-1]
        self.days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Weekend']
        self.unit_cost = 4
        self.net_revenue = 7

        # state variables initialization
        self.day = ""
        self.inventory = -1

        # action space setup
        self.actions_list = [0, 100, 200, 300, 400] # number of patties to purchase at the beginning of the day
        self.action_space = gym.spaces.Discrete(len(self.actions_list))

        # observation space setup (fully observable environment: state space and observation space are the same)
        self.state_space = [("Mon", 0)] + [
            (d, i)
            for d in ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Weekend'][1:]
            for i in [0, 100, 200, 300]
        ]
        self.observation_space = gym.spaces.Discrete(len(self.state_space))

    def _get_obs(self):
        return self.state_space.index((self.day, self.inventory))

    def get_next_state_reward(self, state, action, demand):
        day, inventory = state
        result = {}
        result['next_day'] = self.days[self.days.index(day) + 1]
        result['starting_inventory'] = min(self.capacity, inventory + action)
        result['cost'] = self.unit_cost * action
        result['sales'] = min(result['starting_inventory'], demand)
        result['revenue'] = self.net_revenue * result['sales']
        result['next_inventory'] = result['starting_inventory'] - result['sales']
        result['reward'] = result['revenue'] - result['cost']
        return result

    # returns all possible transitions (next state and rewards) for a given state and action pair
    def get_transition_prob(self, state, action):
        next_s_r_prob = {}
        for ix, demand in enumerate(self.v_demand):
            result = self.get_next_state_reward(state, action, demand)
            next_s = (result['next_day'], result['next_inventory'])
            reward = result['reward']
            prob = self.p_demand[ix]

            if (next_s, reward) not in next_s_r_prob:
                next_s_r_prob[next_s, reward] = prob
            else:
                next_s_r_prob[next_s, reward] += prob

        return next_s_r_prob

    def reset(self, seed: Optional[int] = None, options: Optional[dict] = None):
        super().reset(seed=seed)
        self.day = "Mon"
        self.inventory = 0
        observation = self._get_obs()
        info = {} # in this example we are not using info. Instead, you can define your custom '_get_info(self)' method in environment class and call it here.
        return observation, info

    def is_terminal(self, state):
        day, inventory = state
        return day == "Weekend"

    def step(self, action_index):
        # Convert action index back to real action
        action = self.actions_list[action_index]

        demand = np.random.choice(self.v_demand, p=self.p_demand)
        result = self.get_next_state_reward((self.day, self.inventory), action, demand)

        self.day = result['next_day']
        self.inventory = result['next_inventory']

        state = (self.day, self.inventory)
        reward = result['reward']

        terminated = self.is_terminal(state)  # natural termination
        truncated = False                     # no time-limit logic here

        observation = self._get_obs()
        info = {'demand': demand, 'sales': result['sales']}

        return observation, reward, terminated, truncated, info

foodtruck = FoodTruck()
foodtruck.get_transition_prob(("Tue", 200), 100)



"""# Policy Evaluation"""

def base_policy(states):
    policy = {}
    for s in states:
        day, inventory = s
        prob_a = {}
        if inventory >= 300:
            prob_a[0] = 1 # no need to replenish
        else: # replenish to 200 or 300 with equal probability
            prob_a[200 - inventory] = 0.5
            prob_a[300 - inventory] = 0.5
        policy[s] = prob_a
    return policy

foodtruck = FoodTruck()
base_policy(foodtruck.state_space)

def expected_update(env, v, s, prob_a, gamma):
    expected_value = 0
    for a in prob_a:
        prob_next_s_r = env.get_transition_prob(s, a)
        for next_s, r in prob_next_s_r:
            expected_value += prob_a[a] * prob_next_s_r[next_s, r] * (r + gamma * v[next_s])
    return expected_value

"""Iterative Policy Evaluation"""

def iterative_policy_evaluation(env, policy, max_iter=100, v = None, eps=0.1, gamma=1):
    if not v:
        v = {s: 0 for s in env.state_space}
    k = 0
    while True:
        max_delta = 0
        for s in v:
            if not env.is_terminal(s):
                v_old = v[s]
                prob_a = policy[s]
                v[s] = expected_update(env, v, s, prob_a, gamma)
                max_delta = max(max_delta, abs(v[s] - v_old))
        k += 1
        if max_delta < eps:
            print("Converged in", k, "iterations.")
            break
        elif k == max_iter:
            print("Terminating after", k, "iterations.")
            break
    return v

foodtruck = FoodTruck()
policy = base_policy(foodtruck.state_space)

v = iterative_policy_evaluation(foodtruck, policy)
print("Expected weekly profit:", v["Mon", 0])

print("The state values:")
v



"""Simulation with Gym Environment"""

def choose_action(state, policy):
    prob_a = policy[state]
    action = np.random.choice(a=list(prob_a.keys()),
                              p=list(prob_a.values()))
    return action

def simulate_policy(policy, n_episodes):
    np.random.seed(0)
    foodtruck = FoodTruck()
    rewards = []
    for i_episode in range(n_episodes):
        observation, info = foodtruck.reset()
        state = foodtruck.state_space[observation]
        episode_over = False
        ep_reward = 0
        while not episode_over:
            action = choose_action(state, policy)
            action_index = foodtruck.actions_list.index(action)
            observation, reward, terminated, truncated, info = foodtruck.step(action_index)
            state = foodtruck.state_space[observation]
            ep_reward += reward
            episode_over = terminated or truncated
        rewards.append(ep_reward)
    print("Expected weekly profit:", np.mean(rewards))

simulate_policy(policy, 1000)



"""# Policy Iteration"""

# How does a random policy (deterministic) look like?
np.random.seed(1)
policy = {s: {np.random.choice(foodtruck.actions_list): 1} for s in foodtruck.state_space}
print(policy)

# searches for the action that gives the maximum q-value for a given state
def policy_improvement(env, v, s, actions, gamma):
    prob_a = {}
    if not env.is_terminal(s):
        max_q = -np.inf
        best_a = None
        for a in actions:
            q_sa = expected_update(env, v, s, {a: 1}, gamma) # {a: 1} means 100% prob. of taking action a (deterministic approach)
            if q_sa >= max_q:
                max_q = q_sa
                best_a = a
        prob_a[best_a] = 1
    else:
        max_q = 0 #zero q value is returned for terminal states (weekend)
    return prob_a, max_q

def policy_iteration(env,  eps=0.1, gamma=1):
    np.random.seed(1)
    states = env.state_space
    actions = env.actions_list # true actions, not indices in action_space
    policy = {s: {np.random.choice(actions): 1}
             for s in states}
    v = {s: 0 for s in states} # init all v values to zero
    while True:
        v = iterative_policy_evaluation(env, policy, v=v, eps=eps, gamma=gamma)
        old_policy = policy
        policy = {}
        for s in states:
            policy[s], _ = policy_improvement(env, v, s, actions, gamma)
        if old_policy == policy:
            break
    print("Optimal policy found!")
    return policy, v

policy, v = policy_iteration(foodtruck)
print("Expected weekly profit:", v["Mon", 0])

policy



"""# Value Iteration"""

def value_iteration(env, max_iter=100, eps=0.1, gamma=1):
    states = env.state_space
    actions = env.actions_list
    v = {s: 0 for s in states}
    policy = {}
    k = 0
    while True:
        max_delta = 0
        for s in states:
            old_v = v[s]
            policy[s], v[s] = policy_improvement(env,
                                                 v,
                                                 s,
                                                 actions,
                                                 gamma)
            max_delta = max(max_delta, abs(v[s] - old_v))
        k += 1
        if max_delta < eps:
            print("Converged in", k, "iterations.")
            break
        elif k == max_iter:
            print("Terminating after", k, "iterations.")
            break
    return policy, v

policy, v = value_iteration(foodtruck)
print("Expected weekly profit:", v["Mon", 0])

policy





"""# Monte Carlo (MC) Methods

## MC Prediction
"""

def first_visit_return(returns, trajectory, gamma):
    G = 0
    T = len(trajectory) - 1
    for t, sar in enumerate(reversed(trajectory)):
        s, a, r = sar
        G = r + gamma * G
        first_visit = True
        for j in range(T - t):
            if s == trajectory[j][0]:
                first_visit = False
        if first_visit: # in the trajectory
            if s in returns:
                returns[s].append(G)
            else:
                returns[s] = [G]
    return returns

# simulates the environment for a single episode with a given policy and returns a trajectory
def get_trajectory(env, policy):
    trajectory = []
    observation, info = env.reset()
    state = env.state_space[observation] # convert gymnasium observation to state
    episode_over = False
    sar = [state]
    while not episode_over:
        action = choose_action(state, policy)
        action_index = foodtruck.actions_list.index(action) # action index is needed for step function (it uses discrete action space 0,1,...)
        observation, reward, terminated, truncated, info = env.step(action_index)
        state = env.state_space[observation]
        sar.append(action)
        sar.append(reward)
        trajectory.append(sar)
        sar = [state]
        episode_over = terminated or truncated
    return trajectory

def first_visit_mc(env, policy, gamma, n_trajectories):
    np.random.seed(0)
    returns = {}
    v = {}
    for i in range(n_trajectories):
        trajectory = get_trajectory(env, policy)
        returns = first_visit_return(returns,
                                     trajectory,
                                     gamma)
    for s in env.state_space:
        if s in returns:
            v[s] = np.round(np.mean(returns[s]), 1)
    return v

foodtruck = FoodTruck()
policy = base_policy(foodtruck.state_space)

v_est = first_visit_mc(foodtruck, policy, 1, 10000)
v_est

v_true = iterative_policy_evaluation(foodtruck, policy)
v_true



"""## On-policy Monte Carlo Control"""

def get_eps_greedy(actions, eps, a_best):
    prob_a = {}
    n_a = len(actions)
    for a in actions:
        if a == a_best:
            prob_a[a] = 1 - eps + eps/n_a
        else:
            prob_a[a] = eps/n_a
    return prob_a

def get_random_policy(states, actions):
    policy = {}
    n_a = len(actions)
    for s in states:
        policy[s] = {a: 1/n_a for a in actions}
    return policy

import operator

def on_policy_first_visit_mc(env, n_iter, eps, gamma):
    np.random.seed(0)
    states =  env.state_space
    actions = env.actions_list
    policy =  get_random_policy(states, actions)
    Q = {s: {a: 0 for a in actions} for s in states}
    Q_n = {s: {a: 0 for a in actions} for s in states}
    for i in range(n_iter):
        if i % 10000 == 0:
            print("Iteration:", i)
        trajectory = get_trajectory(env, policy)
        G = 0
        T = len(trajectory) - 1
        for t, sar in enumerate(reversed(trajectory)):
            s, a, r = sar
            G = r + gamma * G
            first_visit = True
            for j in range(T - t):
                s_j = trajectory[j][0]
                a_j = trajectory[j][1]
                if (s, a) == (s_j, a_j):
                    first_visit = False
            if first_visit:
                Q[s][a] = Q_n[s][a] * Q[s][a] + G
                Q_n[s][a] += 1
                Q[s][a] /= Q_n[s][a]
                a_best = max(Q[s].items(), key=operator.itemgetter(1))[0]
                policy[s] = get_eps_greedy(actions, eps, a_best)
    return policy, Q, Q_n

policy, Q, Q_n = on_policy_first_visit_mc(foodtruck, 300000, 0.05, 1)

policy

Q



"""## Off-policy Monte Carlo Control"""

def off_policy_mc(env, n_iter, eps, gamma):
    np.random.seed(0)
    states =  env.state_space
    actions = env.actions_list
    Q = {s: {a: 0 for a in actions} for s in states}
    C = {s: {a: 0 for a in actions} for s in states}
    target_policy = {}
    behavior_policy = get_random_policy(states,
                                        actions)
    for i in range(n_iter):
        if i % 10000 == 0:
            print("Iteration:", i)
        trajectory = get_trajectory(env,
                                    behavior_policy)
        G = 0
        W = 1
        T = len(trajectory) - 1
        for t, sar in enumerate(reversed(trajectory)):
            s, a, r = sar
            G = r + gamma * G
            C[s][a] += W
            Q[s][a] += (W/C[s][a]) * (G - Q[s][a])
            a_best = max(Q[s].items(),
                         key=operator.itemgetter(1))[0]
            target_policy[s] = a_best
            behavior_policy[s] = get_eps_greedy(actions,
                                                eps,
                                                a_best)
            if a != target_policy[s]:
                break
            W = W / behavior_policy[s][a]
    target_policy = {s: target_policy[s] for s in states
                                   if s in target_policy}
    return target_policy, Q

policy, Q = off_policy_mc(foodtruck, 300000, 0.05, 1)

policy

Q



"""# TD Learning

## TD Prediction
"""

def one_step_td_prediction(env, policy, gamma, alpha, n_iter):
    np.random.seed(0)
    states = env.state_space
    v = {s: 0 for s in states}
    observation, info = env.reset()
    s = env.state_space[observation]
    for i in range(n_iter):
        a = choose_action(s, policy)
        action_index = env.actions_list.index(a)
        observation, reward, terminated, truncated, info = env.step(action_index)
        s_next = env.state_space[observation]
        v[s] += alpha * (reward + gamma * v[s_next] - v[s])
        if terminated or truncated:
            observation, info = env.reset()
            s = env.state_space[observation]
        else:
            s = s_next
    return v

policy = base_policy(foodtruck.state_space)
v = one_step_td_prediction(foodtruck, policy, 1, 0.01, 100000)
v



"""### SARSA"""

def sarsa(env, gamma, eps, alpha, n_iter):
    np.random.seed(0)
    states = env.state_space
    actions = env.actions_list
    Q = {s: {a: 0 for a in actions} for s in states}
    policy = get_random_policy(states, actions)
    observation, info = env.reset()
    s = env.state_space[observation]
    a = choose_action(s, policy)
    action_index = env.actions_list.index(a)
    for i in range(n_iter):
        if i % 100000 == 0:
            print("Iteration:", i)
        observation, reward, terminated, truncated, info = env.step(action_index)
        s_next = env.state_space[observation]
        a_best = max(Q[s_next].items(), key=operator.itemgetter(1))[0]
        policy[s_next] = get_eps_greedy(actions, eps, a_best)
        a_next = choose_action(s_next, policy)
        Q[s][a] += alpha * (reward + gamma * Q[s_next][a_next] - Q[s][a])
        if terminated or truncated:
            observation, info = env.reset()
            s = env.state_space[observation]
            a_best = max(Q[s].items(), key=operator.itemgetter(1))[0]
            policy[s] = get_eps_greedy(actions, eps, a_best)
            a = choose_action(s, policy)
            action_index = env.actions_list.index(a)
        else:
            s = s_next
            a = a_next
    return policy, Q

policy, Q = sarsa(foodtruck, 1, 0.1, 0.01, 1000000)

policy

Q



"""### Q-learning"""

def q_learning(env, gamma, eps, alpha, n_iter):
    np.random.seed(0)
    states =  env.state_space
    actions = env.actions_list
    Q = {s: {a: 0 for a in actions} for s in states}
    policy = get_random_policy(states, actions)
    observation, info = env.reset()
    s = env.state_space[observation]
    for i in range(n_iter):
        if i % 100000 == 0:
            print("Iteration:", i)
        a_best = max(Q[s].items(), key=operator.itemgetter(1))[0]
        policy[s] = get_eps_greedy(actions, eps, a_best)
        a = choose_action(s, policy)
        action_index = env.actions_list.index(a)
        observation, reward, terminated, truncated, info = env.step(action_index)
        s_next = env.state_space[observation]
        Q[s][a] += alpha * (reward + gamma * max(Q[s_next].values()) - Q[s][a])
        if terminated or truncated:
            observation, info = env.reset()
            s = env.state_space[observation]
        else:
            s = s_next
    policy = {s: {max(policy[s].items(), key=operator.itemgetter(1))[0]: 1}for s in states}
    return policy, Q

policy, Q = q_learning(foodtruck, 1, 0.1, 0.01, 1000000)
policy

